image: archlinux
packages:
  - lowdown
  - ssg
oauth: pages.sr.ht/PAGES:RW
environment:
  site: culhane.top
tasks:
- package: |
    cd $site
    make tar
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
